name: html2hamlet
version: '0.3.0'
synopsis: HTML to Hamlet converter
maintainer: tanaka.hideyuki@gmail.com
description: HTML to Hamlet converter
category: Text
author: Hideyuki Tanaka
homepage: http://github.com/tanakh/html2hamlet

extra-source-files:
- package.yaml

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Text.Hamlet.Html2Hamlet

dependencies:
  - base
  - shakespeare
  - optparse-declarative
  - mtl
  - bytestring
  - text
  - containers
  - http-conduit
  - xml-conduit
  - html-conduit
  - regex-tdfa
  - wl-pprint-text

executables:
  html2hamlet:
    main: Main.hs
    source-dirs: src
    dependencies:
      - html2hamlet
